name: Deploy Static Website to GCS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: 3. Set up Cloud SDK (gcloud)
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: terraform-479314

    - name: 4. Deploy to Google Cloud Storage
      run: |
        gcloud storage rsync personal-website/ gs://my-static-website-gcp-123/ \
          --recursive \
          --delete-unmatched-urls

    - name: 5. Invalidate Cloud CDN Cache (Final Optimization)
      run: |
        # Invalidate cache for the URL Map that serves your site
        gcloud compute url-maps invalidate-cdn-cache static-website-url-map \
          --path "/*"
      if: always()


this right 
